services:
    _defaults:
        autowire: true
        autoconfigure: true
    delivery.datacontainer.deliveries:
        class: CatalogManager\DeliveryBundle\DataContainer\Deliveries
        public: true